sudo: required

language: bash

dist: xenial

services:
  - docker

script:
  - TAG="0.12.0.6"
  - CONT_NAME="cpu-lbry"
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker build -t cultclassik/$CONT_NAME:latest .
  - docker images
  - docker tag cultclassik/$CONT_NAME cultclassik/$CONT_NAME:$TAG
  - docker push cultclassik/$CONT_NAME:$TAG
  - docker push cultclassik/$CONT_NAME:latest
